// Code generated by the Encore v1.46.4 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-spine-3oii.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

/**
 * Client is an API client for the spine-3oii Encore application.
 */
export default class Client {
    public readonly admin: admin.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly books: books.ServiceClient
    public readonly lists: lists.ServiceClient
    public readonly search: search.ServiceClient
    public readonly users: users.ServiceClient


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        const base = new BaseClient(target, options ?? {})
        this.admin = new admin.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.books = new books.ServiceClient(base)
        this.lists = new lists.ServiceClient(base)
        this.search = new search.ServiceClient(base)
        this.users = new users.ServiceClient(base)
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: auth.AuthParams | AuthDataGenerator
}

export namespace admin {
    export interface DashboardData {
        value: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
        }

        /**
         * Endpoint that responds with a hardcoded value.
         * To call it, run in your terminal:
         * curl --header "Authorization: dummy-token" http://localhost:4000/admin
         */
        public async getDashboardData(): Promise<DashboardData> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin`)
            return await resp.json() as DashboardData
        }
    }
}

export namespace auth {
    export interface AuthParams {
        authorization: string
    }

    export interface LoginParams {
        identifier: string
        password: string
    }

    export interface RefreshParams {
        refreshToken: string
    }

    export interface SignupParams {
        email: string
        username: string
        password: string
    }

    export interface TokenPair {
        accessToken: string
        refreshToken: string
    }

    export interface VerifiedUser {
        id: string
        email: string
        username: string
    }

    export interface VerifyParams {
        token: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
        }

        /**
         * Change password endpoint
         */
        public async changePassword(params: {
    userID: string
    currentPassword: string
    newPassword: string
}): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/auth.changePassword`, JSON.stringify(params))
        }

        /**
         * Update login endpoint
         */
        public async login(params: LoginParams): Promise<TokenPair> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth.login`, JSON.stringify(params))
            return await resp.json() as TokenPair
        }

        /**
         * Update logout endpoint
         */
        public async logout(params: {
    refreshToken: string
}): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/auth.logout`, JSON.stringify(params))
        }

        public async refresh(params: RefreshParams): Promise<TokenPair> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth.refresh`, JSON.stringify(params))
            return await resp.json() as TokenPair
        }

        /**
         * Update signup endpoint
         */
        public async signup(params: SignupParams): Promise<TokenPair> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth.signup`, JSON.stringify(params))
            return await resp.json() as TokenPair
        }

        public async verify(params: VerifyParams): Promise<VerifiedUser> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth.verify`, JSON.stringify(params))
            return await resp.json() as VerifiedUser
        }
    }
}

export namespace books {
    export interface BookCreateDto {
        title: string
        isbn: string
        subtitle?: string
        authors: string[]
        publishedDate?: string
        pages?: number
        description?: string
        image?: { [key: string]: string }
        mainCategory?: string
        categories: string[]
    }

    export interface BookDto {
        id: string
        isbn: string
        title: string
        subtitle?: string | null
        authors: string[]
        publishedDate?: string | null
        pages?: number | null
        description?: string | null
        image?: {
            smallThumbnail?: string
            thumbnail?: string
            small?: string
            medium?: string
            large?: string
            extraLarge?: string
        }
        mainCategory?: string | null
        categories: string[]
        createdAt: string
        updatedAt: string
    }

    export interface BookResponse {
        /**
         * Indicates if the request was successful
         */
        success: boolean

        /**
         * Error message if the request failed
         */
        message?: string

        /**
         * Book data, can be a single book or an array of books
         */
        result?: BookDto

        /**
         * Optional pagination metadata
         */
        pagination?: backend.Paginated
    }

    export interface BookUpdateDto {
        title?: string
        isbn?: string
        subtitle?: string
        authors?: string[]
        publishedDate?: string
        pages?: number
        description?: string
        image?: { [key: string]: string }
        mainCategory?: string
        categories?: string[]
    }

    export type ReadingStatus = "NOT_STARTED" | "READING" | "COMPLETED" | "ABANDONED"

    export interface UserBookDto {
        id: string
        userId: string
        bookId: string
        owned: boolean
        readingStatus: ReadingStatus
        review?: string | null
        rating?: number | null
        progress?: number | null
        startedAt?: string | null
        finishedAt?: string | null
        createdAt: string
        updatedAt: string
    }

    export interface UserBookResponse {
        /**
         * Indicates if the request was successful
         */
        success: boolean

        /**
         * Error message if the request failed
         */
        message?: string

        /**
         * UserBook data, can be a single user-book relationship or an array
         */
        result?: UserBookDto | UserBookDto[]

        /**
         * Optional pagination metadata
         */
        pagination?: backend.Paginated
    }

    export interface UserBookUpdateDto {
        owned?: boolean
        readingStatus?: ReadingStatus
        rating?: number | null
        review?: string | null
        progress?: number | null
        startedAt?: string | null
        finishedAt?: string | null
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
        }

        /**
         * Create a new book
         */
        public async createBook(params: BookCreateDto): Promise<BookResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/books`, JSON.stringify(params))
            return await resp.json() as BookResponse
        }

        /**
         * Create a user-book relationship
         */
        public async createUserBook(userId: string, params: {
    bookId: string
    owned?: boolean
    readingStatus?: ReadingStatus
    rating?: number | null
    review?: string | null
    progress?: number | null
    startedAt?: string | null
    finishedAt?: string | null
}): Promise<UserBookResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/users/${encodeURIComponent(userId)}/books`, JSON.stringify(params))
            return await resp.json() as UserBookResponse
        }

        /**
         * Delete a book
         */
        public async deleteBook(id: string): Promise<BookResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/books/${encodeURIComponent(id)}`)
            return await resp.json() as BookResponse
        }

        /**
         * Delete a user-book relationship
         */
        public async deleteUserBook(id: string): Promise<UserBookResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/users/books/${encodeURIComponent(id)}`)
            return await resp.json() as UserBookResponse
        }

        /**
         * Get book details
         */
        public async getBook(id: string): Promise<BookResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/books/${encodeURIComponent(id)}`)
            return await resp.json() as BookResponse
        }

        /**
         * Get all books with optional pagination
         */
        public async getBooks(params: {
    page?: number
    limit?: number
}): Promise<BookResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
                page:  params.page === undefined ? undefined : String(params.page),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/books`, undefined, {query})
            return await resp.json() as BookResponse
        }

        /**
         * Get user-book details
         */
        public async getUserBook(id: string): Promise<UserBookResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/books/${encodeURIComponent(id)}`)
            return await resp.json() as UserBookResponse
        }

        /**
         * Get all user-books with optional pagination
         */
        public async getUserBooks(userId: string, params: {
    page?: number
    limit?: number
}): Promise<UserBookResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
                page:  params.page === undefined ? undefined : String(params.page),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(userId)}/books`, undefined, {query})
            return await resp.json() as UserBookResponse
        }

        /**
         * Update book information
         */
        public async updateBook(id: string, params: {
    data: BookUpdateDto
}): Promise<BookResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/books/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as BookResponse
        }

        /**
         * Update user-book information
         */
        public async updateUserBook(id: string, params: {
    data: UserBookUpdateDto
}): Promise<UserBookResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/users/books/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as UserBookResponse
        }
    }
}

export namespace lists {
    export interface ListCreateDto {
        name: string
        userId: string
    }

    export interface ListDto {
        id: string
        name: string
        userId: string
        createdAt: string
        updatedAt: string
        /**
         * Optionally include list items if needed
         */
        listItems?: ListItemDto[]
    }

    export interface ListItemDto {
        id: string
        listId: string
        userBookId: string
        /**
         * Note: Prisma returns Decimal for this field.
         * Representing it as a string ensures clients handle large or precise values.
         */
        position: number

        createdAt: string
        updatedAt: string
    }

    export interface ListItemResponse {
        /**
         * Indicates if the request was successful
         */
        success: boolean

        /**
         * Error message if the request failed
         */
        message?: string

        /**
         * ListItem data, can be a single list item or an array of list items
         */
        result?: ListItemDto | ListItemDto[]

        /**
         * Optional pagination metadata
         */
        pagination?: backend.Paginated
    }

    export interface ListItemUpdateDto {
        position?: number
    }

    export interface ListResponse {
        /**
         * Indicates if the request was successful
         */
        success: boolean

        /**
         * Error message if the request failed
         */
        message?: string

        /**
         * List data, can be a single list or an array of lists
         */
        result?: ListDto

        /**
         * Optional pagination metadata
         */
        pagination?: backend.Paginated
    }

    export interface ListUpdateDto {
        name?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
        }

        public async addBookToListFromSearch(listId: string, params: {
    isbn: string
    userId: string
}): Promise<ListItemResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/lists/${encodeURIComponent(listId)}/add-from-search`, JSON.stringify(params))
            return await resp.json() as ListItemResponse
        }

        /**
         * Create a new list
         */
        public async createList(params: ListCreateDto): Promise<ListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/lists`, JSON.stringify(params))
            return await resp.json() as ListResponse
        }

        /**
         * Create a new list item
         */
        public async createListItem(listId: string, params: {
    userBookId: string
    /**
     * Optional position allows the database default to apply if omitted
     */
    position: number
}): Promise<ListItemResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/lists/${encodeURIComponent(listId)}/items`, JSON.stringify(params))
            return await resp.json() as ListItemResponse
        }

        /**
         * Delete a list
         */
        public async deleteList(id: string): Promise<ListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/lists/${encodeURIComponent(id)}`)
            return await resp.json() as ListResponse
        }

        /**
         * Delete a list item
         */
        public async deleteListItem(id: string): Promise<ListItemResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/lists/items/${encodeURIComponent(id)}`)
            return await resp.json() as ListItemResponse
        }

        /**
         * Get list details
         */
        public async getList(id: string): Promise<ListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/lists/${encodeURIComponent(id)}`)
            return await resp.json() as ListResponse
        }

        /**
         * Get list item details
         */
        public async getListItem(id: string): Promise<ListItemResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/lists/items/${encodeURIComponent(id)}`)
            return await resp.json() as ListItemResponse
        }

        /**
         * Get all items in a list with optional pagination
         */
        public async getListItems(listId: string, params: {
    page?: number
    limit?: number
}): Promise<ListItemResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
                page:  params.page === undefined ? undefined : String(params.page),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/lists/${encodeURIComponent(listId)}/items`, undefined, {query})
            return await resp.json() as ListItemResponse
        }

        /**
         * Update list information
         */
        public async updateList(id: string, params: {
    data: ListUpdateDto
}): Promise<ListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/lists/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as ListResponse
        }

        /**
         * Update list item information
         */
        public async updateListItem(id: string, params: {
    data: ListItemUpdateDto
}): Promise<ListItemResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/lists/items/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as ListItemResponse
        }
    }
}

export namespace search {
    export interface SearchParams {
        query: string
        maxResults?: number
        startIndex?: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
        }

        /**
         * Search Google Books API
         */
        public async search(params: SearchParams): Promise<src.SearchResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                maxResults: params.maxResults === undefined ? undefined : String(params.maxResults),
                query:      params.query,
                startIndex: params.startIndex === undefined ? undefined : String(params.startIndex),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/search`, undefined, {query})
            return await resp.json() as src.SearchResponse
        }
    }
}

export namespace users {
    export interface UserCreateDto {
        username: string
        email: string
        password: string
        /**
         * "name" is optional.
         */
        name?: string | null
    }

    export interface UserDto {
        id: string
        username: string
        email: string
        password: string
        /**
         * Optional since "name" can be null in the Prisma model.
         */
        name?: string | null

        createdAt: string
        updatedAt: string
    }

    export interface UserResponse {
        /**
         * Indicates if the request was successful
         */
        success: boolean

        /**
         * Error message if the request failed
         */
        message?: string

        /**
         * User data, can be a single user or an array of users
         */
        result?: UserDto | UserDto[]

        /**
         * Optional pagination metadata
         */
        pagination?: backend.Paginated
    }

    export interface UserUpdateDto {
        username?: string
        email?: string
        password?: string
        name?: string | null
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
        }

        /**
         * Counts and returns the number of existing users
         */
        public async count(): Promise<backend.Response> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/count/users`)
            return await resp.json() as backend.Response
        }

        /**
         * Method to create a new user
         */
        public async create(params: UserCreateDto): Promise<UserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/users`, JSON.stringify(params))
            return await resp.json() as UserResponse
        }

        /**
         * Delete user by id
         */
        public async destroy(id: string): Promise<backend.Response> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/users/${encodeURIComponent(id)}`)
            return await resp.json() as backend.Response
        }

        /**
         * Get all users data
         */
        public async read(params: {
    page?: number
    limit?: number
}): Promise<UserResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
                page:  params.page === undefined ? undefined : String(params.page),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users`, undefined, {query})
            return await resp.json() as UserResponse
        }

        /**
         * Get user data by id
         */
        public async readOne(id: string): Promise<UserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(id)}`)
            return await resp.json() as UserResponse
        }

        /**
         * Update user data
         */
        public async update(id: string, params: {
    data: UserUpdateDto
}): Promise<UserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/users/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as UserResponse
        }
    }
}

export namespace backend {
    export interface Paginated {
        /**
         * Total number of results
         */
        count: number

        /**
         * Number of results per page
         */
        pageSize: number

        /**
         * Total number of pages
         */
        totalPages: number

        /**
         * Current page number
         */
        current: number
    }

    export interface Response {
        /**
         * Indicates if the request was successful
         */
        success: boolean

        /**
         * Error message if the request was not successful
         */
        message?: string

        /**
         * The result of the request (number or string)
         */
        result?: string | number
    }
}

export namespace src {
    export interface SearchResponse {
        results: SearchResult[]
        totalResults: number
        hasMore: boolean
    }

    export interface SearchResult {
        id: string
        isbn: string | null
        title: string
        authors: string[]
        thumbnail: string | null
        publishedDate: string | null
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | auth.AuthParams
  | Promise<auth.AuthParams | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (typeof window === "undefined") {
            this.headers["User-Agent"] = "spine-3oii-Generated-TS-Client (Encore/v1.46.4)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: auth.AuthParams | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: BodyInit, params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: BodyInit, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
