import { PrismaClient } from "@prisma/client";
import { SQLDatabase } from "encore.dev/storage/sqldb";

// Define a database named 'encore_prisma_test', using the database migrations
// in the "./prisma/migrations" folder (where prisma will generate their migrations).
// Set `source` to `prisma` to let Encore know that the migrations are generated by Prisma.
const DB = new SQLDatabase("spine-dev", {
	migrations: {
		path: "./prisma/migrations",
		source: "prisma",
	},
});

// Setup prisma client with connection string
const prisma = new PrismaClient({
	datasources: {
		db: {
			url: DB.connectionString,
		},
	},
});

export default prisma;
